name: burger_1d
equation: "burger"

# simple | siren
model:
  type: "simple"
  dims: [2, 100, 100, 100, 100, 100, 1]

decomposition:
  steps: 1
  time_axis: 0
  type: "initial"

mesh:
  file: "meshes/burger_1d.obj"
  bulk_points: 8192
  boundary_points: 1366
  initial_points: 682

training:
  scheduler: false
  epochs: 8000
  lr: 1e-3
  weights:
    bulk: 1.0
    boundary: 1.0
    initial: 1.0

checkpoint:
  enabled: false
  interval: 100

logging:
  enabled: true
  level: "INFO"