# config/default.yaml
name: wave_rectangle
data: "meshes/rectangle_wave.pkl"

# wave | heat | laplace | eikonal
equation: "wave"

# simple | siren
model:
  type: "simple"
  dims: [2, 128, 128, 128, 128, 1]

mesh:
  file: "meshes/rectangle.obj"
  steps: 1
  time_axis: 0
  bulk_points: 2000
  boundary_points: 2000
  initial_points: 1000

training:
  scheduler: true
  epochs: 48000
  lr: 1e-4
  weights:
    bulk: 1.0
    boundary: 1.0
    initial: 1.0

checkpoint:
  enabled: false
  interval: 100

logging:
  enabled: true
  level: "INFO"